export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  // Candidate Domain Errors
  CANDIDATE_NOT_FOUND: "CANDIDATE_NOT_FOUND",
  CANDIDATE_ALREADY_EXISTS: "CANDIDATE_ALREADY_EXISTS",
  CANDIDATE_ACCESS_DENIED: "CANDIDATE_ACCESS_DENIED",
  EXPERIENCE_NOT_FOUND: "EXPERIENCE_NOT_FOUND",
  EDUCATION_NOT_FOUND: "EDUCATION_NOT_FOUND",
  SKILL_ALREADY_EXISTS: "SKILL_ALREADY_EXISTS",
  SKILL_NOT_FOUND: "SKILL_NOT_FOUND",
  PREFERENCES_NOT_FOUND: "PREFERENCES_NOT_FOUND",
  INVALID_CANDIDATE_STATE: "INVALID_CANDIDATE_STATE",
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
