import type { Job } from "./jobs-types"

export const JOB_FIXTURES: Job[] = [
  {
    id: "job_vela_backend_sr",
    slug: "senior-backend-engineer-vela-systems",
    title: "Senior Backend Engineer",
    company: "Vela Systems",
    companyLogoText: "VS",
    location: {
      city: "San Francisco",
      state: "CA",
      country: "USA",
      workType: "hybrid",
    },
    employmentType: "full-time",
    seniority: "senior",
    salary: { currency: "USD", min: 175000, max: 215000, interval: "year" },
    source: "lever",
    sourceUrl: "https://jobs.lever.co/vela-systems/sr-backend",
    postedAt: "2026-09-08T10:00:00Z",
    updatedAt: "2026-09-08T10:00:00Z",
    overview:
      "Vela Systems develops real-time telemetry infrastructure for mission-critical industrial assets. We are hiring a Senior Backend Engineer to architect low-latency event processing services, maintain transactional consistency across distributed clusters, and build robust developer APIs.",
    responsibilities: [
      "Architect and scale distributed stream ingestion handling 50k+ events/sec.",
      "Design fault-tolerant storage schemas across PostgreSQL and timeseries databases.",
      "Collaborate with hardware and edge engineers to standardize telemetry protocols.",
      "Lead architectural reviews and mentor junior and mid-level software engineers.",
    ],
    requirements: [
      "5+ years of production experience in distributed backend systems.",
      "Strong proficiency in TypeScript / Node.js, Go, or Rust.",
      "Deep understanding of relational database indexing, transactions, and performance tuning.",
      "Hands-on experience with Kafka, Redis, or similar high-throughput messaging brokers.",
    ],
    niceToHave: [
      "Experience with industrial IoT protocols or MQTT brokers.",
      "Familiarity with Kubernetes operator patterns and Terraform infrastructure.",
    ],
    benefits: [
      "Competitive base salary with equity options.",
      "Comprehensive medical, dental, and vision insurance with 100% premium coverage.",
      "401(k) retirement match up to 4%.",
      "Annual $3,000 professional development and learning stipend.",
    ],
    tags: ["Go", "TypeScript", "PostgreSQL", "Kafka", "Distributed Systems"],
  },
  {
    id: "job_syntropy_frontend_staff",
    slug: "staff-frontend-architect-syntropy",
    title: "Staff Frontend Architect",
    company: "Syntropy",
    companyLogoText: "SY",
    location: { city: "Remote", country: "USA", workType: "remote" },
    employmentType: "full-time",
    seniority: "staff",
    salary: { currency: "USD", min: 195000, max: 245000, interval: "year" },
    source: "greenhouse",
    sourceUrl: "https://boards.greenhouse.io/syntropy/staff-frontend",
    postedAt: "2026-09-06T14:30:00Z",
    updatedAt: "2026-09-07T09:15:00Z",
    overview:
      "Syntropy builds unified analytics surfaces for cloud infrastructure security. We are seeking a Staff Frontend Architect to govern our multi-app web ecosystem, establish cross-cutting design system standards, and ensure 60fps data visualization performance across high-density dashboards.",
    responsibilities: [
      "Own the technical direction, performance budgets, and build pipeline for all web applications.",
      "Partner with product design to scale an accessible, tokenized design system.",
      "Optimize complex canvas, SVG, and WebGL rendering for network graph visualizers.",
      "Champion front-end testing methodologies and engineering excellence standards.",
    ],
    requirements: [
      "8+ years engineering production web applications, with 3+ years in architectural leadership.",
      "Mastery of modern React (React 19), Next.js App Router, TypeScript, and CSS architecture.",
      "Proven track record building and maintaining multi-brand design systems.",
      "Strong commitment to WCAG 2.1 AA accessibility and cross-browser resilience.",
    ],
    niceToHave: [
      "Experience with Turborepo monorepo orchestration and micro-frontends.",
      "Contributions to open-source UI libraries or developer tooling.",
    ],
    benefits: [
      "100% remote flexibility with home office setup budget.",
      "Unlimited flexible PTO with mandatory minimum vacation guidance.",
      "Top-tier health coverage + HSA contribution.",
      "Annual company retreats in international locations.",
    ],
    tags: [
      "React 19",
      "Next.js",
      "TypeScript",
      "Design Systems",
      "Accessibility",
    ],
  },
  {
    id: "job_kestrel_ml_applied",
    slug: "applied-ai-engineer-kestrel-ai",
    title: "Applied AI Engineer",
    company: "Kestrel AI",
    companyLogoText: "KA",
    location: {
      city: "Seattle",
      state: "WA",
      country: "USA",
      workType: "hybrid",
    },
    employmentType: "full-time",
    seniority: "senior",
    salary: { currency: "USD", min: 180000, max: 230000, interval: "year" },
    source: "greenhouse",
    sourceUrl: "https://boards.greenhouse.io/kestrelai/applied-ai-sr",
    postedAt: "2026-09-05T18:00:00Z",
    updatedAt: "2026-09-05T18:00:00Z",
    overview:
      "Kestrel AI develops verified retrieval and reasoning agents for enterprise legal teams. As an Applied AI Engineer, you will build production evaluation harnesses, fine-tune domain-specific language models, and construct high-scale semantic retrieval pipelines.",
    responsibilities: [
      "Construct hybrid vector and lexical search engines powered by pgvector and OpenSearch.",
      "Implement automated evaluation pipelines to benchmark hallucination rates and answer relevance.",
      "Optimize model inference latencies using TensorRT-LLM and vLLM clusters.",
      "Deploy safe tool-calling agents with strict schema validation and auditing.",
    ],
    requirements: [
      "4+ years of software engineering experience with 2+ years deploying LLM pipelines.",
      "Proficiency with Python, PyTorch, LangChain/LlamaIndex, and vector databases.",
      "Demonstrated ability to move from research prototype to production service with SLAs.",
      "Solid foundation in information retrieval, embedding spaces, and precision/recall metrics.",
    ],
    niceToHave: [
      "Published research or open source contributions in NLP or retrieval systems.",
      "Experience deploying inference workloads on Kubernetes with GPU operator.",
    ],
    benefits: [
      "Generous equity package in early-growth stage company.",
      "Premium health, dental, and life insurance.",
      "Daily catered lunches at our Seattle downtown waterfront office.",
    ],
    tags: ["Python", "PyTorch", "pgvector", "LLMs", "Information Retrieval"],
  },
  {
    id: "job_prisma_fullstack",
    slug: "full-stack-systems-engineer-prisma-labs",
    title: "Full-Stack Systems Engineer",
    company: "Prisma Labs",
    companyLogoText: "PL",
    location: {
      city: "New York",
      state: "NY",
      country: "USA",
      workType: "hybrid",
    },
    employmentType: "full-time",
    seniority: "mid",
    salary: { currency: "USD", min: 150000, max: 185000, interval: "year" },
    source: "direct",
    sourceUrl: "https://prismalabs.io/careers/fullstack-systems",
    postedAt: "2026-09-04T11:20:00Z",
    updatedAt: "2026-09-04T11:20:00Z",
    overview:
      "Prisma Labs develops developer-first database automation and migration tools. We are seeking a Full-Stack Systems Engineer who enjoys working across the entire stack—from CLI tools and database drivers to responsive interactive web consoles.",
    responsibilities: [
      "Build real-time database query inspection and migration visualization consoles.",
      "Develop type-safe RPC endpoints linking our cloud coordinator to client interfaces.",
      "Write comprehensive end-to-end integration tests and benchmark system latency.",
    ],
    requirements: [
      "3+ years experience across modern TypeScript (Node.js & React).",
      "Strong understanding of PostgreSQL internals, query planners, and schema migrations.",
      "Experience with state management, WebSockets, and optimistic client updates.",
    ],
    niceToHave: ["Familiarity with Rust or WebAssembly (Wasm)."],
    benefits: [
      "Flexible working hours.",
      "Full healthcare benefits.",
      "Wellness stipend.",
    ],
    tags: ["TypeScript", "React", "PostgreSQL", "TailwindCSS", "Node.js"],
  },
  {
    id: "job_apex_cloud_infra",
    slug: "cloud-infrastructure-engineer-apex-data",
    title: "Cloud Infrastructure Engineer",
    company: "Apex Data",
    companyLogoText: "AD",
    location: { city: "Remote", country: "Global", workType: "remote" },
    employmentType: "full-time",
    seniority: "senior",
    salary: { currency: "USD", min: 165000, max: 210000, interval: "year" },
    source: "workday",
    sourceUrl: "https://apexdata.wd1.myworkdayjobs.com/careers/cloud-infra",
    postedAt: "2026-09-03T08:00:00Z",
    updatedAt: "2026-09-03T08:00:00Z",
    overview:
      "Apex Data processes petabyte-scale genomics workflows. We are looking for a Cloud Infrastructure Engineer to manage multi-region AWS infrastructure, automate zero-downtime deployment pipelines, and optimize compute workloads.",
    responsibilities: [
      "Manage Kubernetes clusters and GitOps workflows across multiple cloud regions.",
      "Automate infrastructure provisioning using Terraform, OpenTofu, and Terragrunt.",
      "Implement comprehensive observability stacks using Prometheus, Grafana, and OpenTelemetry.",
    ],
    requirements: [
      "5+ years in DevOps, SRE, or Cloud Infrastructure roles.",
      "Hands-on mastery of Kubernetes in production environments.",
      "Strong scripting skills in Python, Bash, or Go.",
    ],
    niceToHave: [
      "Experience with large-scale batch processing (Argo Workflows, Nextflow).",
    ],
    benefits: [
      "Remote work anywhere in Americas or EMEA.",
      "Learning & conference budget.",
    ],
    tags: ["AWS", "Kubernetes", "Terraform", "SRE", "Prometheus"],
  },
  {
    id: "job_crucible_db_systems",
    slug: "distributed-database-engineer-crucible-db",
    title: "Distributed Database Systems Engineer",
    company: "Crucible DB",
    companyLogoText: "CD",
    location: {
      city: "San Francisco",
      state: "CA",
      country: "USA",
      workType: "on-site",
    },
    employmentType: "full-time",
    seniority: "staff",
    salary: { currency: "USD", min: 195000, max: 250000, interval: "year" },
    source: "greenhouse",
    sourceUrl: "https://boards.greenhouse.io/crucibledb/db-systems",
    postedAt: "2026-09-01T15:00:00Z",
    updatedAt: "2026-09-02T10:00:00Z",
    overview:
      "Crucible DB is building a next-generation transactional storage engine designed for modern NVMe hardware. We are seeking a systems programmer to work on our consensus engine and LSM storage tier.",
    responsibilities: [
      "Implement Raft consensus extensions for multi-datacenter quorum replication.",
      "Optimize disk I/O with io_uring and zero-copy memory buffers.",
      "Write deterministic simulation tests to detect edge-case partition splits.",
    ],
    requirements: [
      "6+ years writing systems software in Rust or C++.",
      "Deep understanding of distributed systems theory (Paxos/Raft, CAP, ACID).",
      "Experience with concurrent lock-free data structures and Linux memory models.",
    ],
    niceToHave: [
      "Past contributions to RocksDB, TiKV, CockroachDB, or SQLite.",
    ],
    benefits: [
      "Top 1% equity grants.",
      "Full family medical & dental.",
      "Commuter benefits.",
    ],
    tags: ["Rust", "Distributed Systems", "C++", "Storage Engines", "Raft"],
  },
]
